AWSTemplateFormatVersion: '2010-09-09'
Description: IAM User for running Infrastructure as Code (Terraform)

Parameters:
  TerraformUserName:
    Type: String
    Default: Adex
    Description: IAM user name for Terraform

Resources:
  TerraformUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref TerraformUserName

  TerraformPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: TerraformExecPolicy
      Users:
        - !Ref TerraformUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ec2:*
              - logs:*
            Resource: "*"

          - Effect: Allow
            Action:
              - iam:GetRole
              - iam:PassRole
              - iam:CreateRole
              - iam:DeleteRole
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:CreateInstanceProfile 
              - iam:TagRole
              - iam:ListRolePolicies
              - iam:ListAttachedRolePolicies
              - iam:CreateInstanceProfile
              - iam:DeleteInstanceProfile
              - iam:AddRoleToInstanceProfile
              - iam:RemoveRoleFromInstanceProfile
              - iam:ListInstanceProfilesForRole
              - iam:GetInstanceProfile
            Resource: "*"

          - Effect: Allow
            Action:
              - s3:*
            Resource: "*"

          - Effect: Allow
            Action:
              - route53:ListHostedZones
              - route53:GetHostedZone
              - route53:ListResourceRecordSets
              - route53:ChangeResourceRecordSets
              - route53:ListTagsForResource
              - route53:GetChange
              - route53:CreateHostedZone
              - route53:DeleteHostedZone

            Resource: "*"

          - Effect: Allow
            Action:
              - sts:GetCallerIdentity
            Resource: "*"

  TerraformAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref TerraformUser

  TerraformSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: terraform/iam/Adex
      Description: Terraform IAM Credentials
      SecretString: !Sub |
        {
          "AWS_ACCESS_KEY_ID": "${TerraformAccessKey}",
          "AWS_SECRET_ACCESS_KEY": "${TerraformAccessKey.SecretAccessKey}"
        }

Outputs:
  TerraformUserName:
    Value: !Ref TerraformUser

  TerraformSecretName:
    Value: terraform/iam/Adex
