AWSTemplateFormatVersion: "2010-09-09"
Description: IAM User and Policy for Terraform

Parameters:
  TerraformUserName:
    Type: String
    Default: Adex
    Description: IAM user name for Terraform

Resources:
  TerraformUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref TerraformUserName

  TerraformPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: TerraformExecPolicy
      Users:
        - !Ref TerraformUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ec2:*
              - logs:*
            Resource: "*"

          - Effect: Allow
            Action:
              - iam:GetRole
              - iam:PassRole
              - iam:CreateRole
              - iam:DeleteRole
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:CreateInstanceProfile
              - iam:DeleteInstanceProfile
              - iam:AddRoleToInstanceProfile
              - iam:RemoveRoleFromInstanceProfile
              - iam:ListInstanceProfilesForRole
              - iam:GetInstanceProfile
              - iam:ListRolePolicies
              - iam:ListAttachedRolePolicies
              - iam:TagRole
            Resource: "*"

          - Effect: Allow
            Action:
              - s3:*
            Resource: "*"

          - Effect: Allow
            Action:
              - route53:ListHostedZones
              - route53:GetHostedZone
              - route53:ListResourceRecordSets
              - route53:ChangeResourceRecordSets
              - route53:ListTagsForResource

            Resource: "*"

          - Effect: Allow
            Action:
              - sts:GetCallerIdentity
            Resource: "*"

Outputs:
  TerraformUserName:
    Value: !Ref TerraformUser
    Export:
      Name: TerraformUserName
