AWSTemplateFormatVersion: '2010-09-09'
Description: Terraform IAM Access Keys stored in Secrets Manager

Parameters:
  TerraformUserName:
    Type: String
    Default: Adex
    Description: IAM user name (must already exist)

Resources:
  TerraformAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref TerraformUserName

  TerraformSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: terraform/iam/Adex
      Description: Terraform IAM Credentials
      SecretString: !Sub |
        {
          "AWS_ACCESS_KEY_ID": "${TerraformAccessKey}",
          "AWS_SECRET_ACCESS_KEY": "${TerraformAccessKey.SecretAccessKey}"
        }

Outputs:
  TerraformSecretName:
    Value: terraform/iam/Adex
